# Generated by Django 4.0.2 on 2022-03-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amail',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amail',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
