# Generated by Django 4.0.2 on 2022-03-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_amail_replied_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='amail',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'With gratitude your friend Mahsa'), ('2', 'Respectfully Mahsa'), ('3', ' Sincerely yours Mahsa'), ('4', 'Stay safe and well')], max_length=1, null=True),
        ),
    ]
