# Generated by Django 4.0.2 on 2022-03-27 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_amail_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amail',
            old_name='gender',
            new_name='signature',
        ),
    ]
