# Generated by Django 4.0.2 on 2022-03-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_gender_amail_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amail',
            name='signature',
            field=models.CharField(blank=True, choices=[('With gratitude your friend Mahsa', 'With gratitude your friend Mahsa'), ('Respectfully Mahsa', 'Respectfully Mahsa'), (' Sincerely yours Mahsa', ' Sincerely yours Mahsa'), ('Stay safe and well', 'Stay safe and well')], max_length=50, null=True),
        ),
    ]
