# Generated by Django 4.0.2 on 2022-03-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_amail_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='amail',
            name='is_filter',
            field=models.BooleanField(default=False),
        ),
    ]
