# Generated by Django 4.0.2 on 2022-04-05 18:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_amail_is_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amail',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
