# Generated by Django 4.0.2 on 2022-02-24 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amail',
            name='receiver_email',
        ),
        migrations.AddField(
            model_name='amail',
            name='receiver_email',
            field=models.ManyToManyField(to='main.Contacts'),
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='user',
        ),
        migrations.AddField(
            model_name='contacts',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
